### ISSUE TITLE
2 Paths in MeepMeep Simulator

### ISSUE THREAD

**Issue by MatthewSong86** [6165-MSET-CuttleFish/PowerPlay#1]
Create one path for each blue side in MeepMeep. There should be at least 3 cycles in this path.

**Comment by MatthewSong86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2 Blue Paths in your own branch](https://trello.com/c/PpJuod35/1-2-blue-paths-in-your-own-branch)

**Comment by SreyashDasSarma** [comment]
Srey's Paths: https://github.com/6165-MSET-CuttleFish/PowerPlay/pull/2#issue-1373914655
